### ISSUE TITLE
SDA & SCL not passed on with begin()

### ISSUE THREAD

**Issue by videobuff** [adafruit/Adafruit_FT6206_Library#18]
- Arduino board:  **WT32-SCO1 with ESP32**

- Arduino IDE version (found in Arduino -> About Arduino menu):  **1.8.19**

 **LIST REPRO STEPS BELOW**

If i give the SDA & SCL pins as parameters in the begin function, it does not work.
If ihard code these pins in the library Adafruit_FT6206.cpp then i works.

I use the example sketches:\

where is says

```
if (!ts.begin(40)) { 
    Serial.println("Unable to start touchscreen.");
  } 
  else { 
    Serial.println("Touchscreen started."); 
  }
```

But from the library I read that i can also use SDA,SCL and TRESHOLD so i tried

```
f (!ts.begin(18,19, 40)) { 
    Serial.println("Unable to start touchscreen.");
  } 
  else { 
    Serial.println("Touchscreen started."); 
  }
```

This, however, does not work...
This is how i solved it for the moment in Adafruit_FT6206.cpp

```
boolean Adafruit_FT6206::begin(uint8_t sda, uint8_t scl, uint8_t thresh) {
  if (sda == 0 && scl == 0) {
    Wire.begin();
  } else {
    Wire.begin(sda, scl);
      
      // not working with variables sda and scl, but if change with hardcoded
      // pins works -> Wire.begin(18, 19); then it works perfectly.
  }

```

**Comment by ladyada** [comment]
https://github.com/espressif/arduino-esp32/issues/3779
