### ISSUE TITLE
Qualia Learn Guide mentions setting I2C address, currently not possible

### ISSUE THREAD

**Issue by tyeth** [adafruit/Adafruit_FT6206_Library#21]
https://learn.adafruit.com/adafruit-qualia-esp32-s3-for-rgb666-displays/arduino-touch-display-usage
Also https://learn.adafruit.com/adafruit-qualia-esp32-s3-for-rgb666-displays/arduino-rainbow-demo

Code example used:
```cpp
#include <Wire.h>      // this is needed for FT6206
#include <Adafruit_FT6206.h>

#define I2C_TOUCH_ADDR 0x48  // often but not always 0x48!
Adafruit_FT6206 ctp = Adafruit_FT6206();  // this library also supports FT5336U!

Serial.begin(115200);  // To print the output

if (!ctp.begin(0, &Wire, I2C_TOUCH_ADDR)) {
    Serial.println("No touchscreen found");
}
```

**Comment by brentru** [comment]
@makermelissa  Could you take a look at this?

**Comment by makermelissa** [comment]
Yeah, looking at the code, this appears to be the case. It looks like a default third parameter needs to be added to begin.

**Comment by ladyada** [comment]
my error - now pushed
