### ISSUE TITLE
Make private methods protected

### ISSUE THREAD

**Issue by romansavrulin** [adafruit/Adafruit_FT6206_Library#7]
Hello, @ladyada. I'm wondering why do you make all methods in the classes you implement private, not protected?

Doing so makes it hard to inherit from your classes's code and implement some specific behavior.

We are using some of your libraries in [our project](https://github.com/libEmGUI) and in each library we have to deal with exactly the same issue - private methods. So we have to fork your lib, edit private-protected, inherit class to add our own logic

**Comment by ladyada** [comment]
habit :) if you submit a PR for private -> protected i'll look to merge it as long as it still builds and works

**Comment by ladyada** [comment]
stale issue, reopen if you still need it!
