### ISSUE TITLE
Compile error when I used Adafruit_FT6206 library with Adafruit_GFX

### ISSUE THREAD

**Issue by sudni** [adafruit/Adafruit_FT6206_Library#8]
Context
- Arduino board:  UNO 
- TFT Screen ER-TFTM028-4 V4.0
- Arduino IDE version:  Arduino 1.8.9 (Windows Store 1.8.21.0)

Hi, I used with my UNO card with an TFT screen ER-TFTM028-4. The GFX work well with demo example. But when I try demo of capacitve touch screen, I've compilation error.

C:\Users\paul_\Documents\Arduino\libraries\Adafruit_GFX_Library\Adafruit_SPITFT.cpp: In member function 'writeFastVLine':
C:\Users\paul_\Documents\Arduino\libraries\Adafruit_GFX_Library\Adafruit_SPITFT.cpp:1318:1: internal compiler error: Segmentation fault

 }

 ^

Please submit a full bug report,

with preprocessed source if appropriate.

See <http://gcc.gnu.org/bugs.html> for instructions.

lto-wrapper.exe: fatal error: C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.21.0_x86__mdqgnx93n4wtt\hardware\tools\avr/bin/avr-gcc returned 1 exit status

compilation terminated.

c:/program files/windowsapps/arduinollc.arduinoide_1.8.21.0_x86__mdqgnx93n4wtt/hardware/tools/avr/bin/../lib/gcc/avr/5.4.0/../../../../avr/bin/ld.exe: error: lto-wrapper failed

collect2.exe: error: ld returned 1 exit status

exit status 1
Erreur de compilation pour la carte Arduino/Genuino Uno

What's the problem ??
Thank in advance for you help,

Paul.

**Comment by ladyada** [comment]
hiya please contact the vendor of  ER-TFTM028-4 for support!
